import AccountUpdate from "src/components/Customer/Account/account.update";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tài khoản của tôi | Tiki",
    description: "Generated by create next app",
};

const Account = () => {
    return (
        <>
            <AccountUpdate />
        </>
    )
}
export default Account;