
import { redirect } from "next/navigation";
import AuthSignin from "src/components/Signin/auth.signin"

export const metadata = {
    title: "Sign in",
    description: "Generated by Next.js",
}

const SignIn = async () => {

    return (
        <>
            <AuthSignin />
        </>
    )
}

export default SignIn;