import AuthSignup from "src/components/signup/auth.signup";

export const metadata = {
    title: "Sign up",
    description: "Generated by Next.js",
}

const SignUpPage = () => {
    return (
        <>
            <AuthSignup />
        </>
    )
}
export default SignUpPage;