import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import AntdStyledComponentsRegistry from "src/lib/AntdStyledComponentsRegistry ";
import 'react-toastify/dist/ReactToastify.css';
import '../styles/main.scss';
import StyledComponentsRegistry from "src/lib/registry";
import StoreProvider from "./StoreProvider";
import NextAuthWrapper from "src/lib/next.auth.wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <NextAuthWrapper>
          <StoreProvider>
            <StyledComponentsRegistry>
              <AntdStyledComponentsRegistry>
                {children}
              </AntdStyledComponentsRegistry>
            </StyledComponentsRegistry>
          </StoreProvider>
          <ToastContainer />
        </NextAuthWrapper>
      </body>
    </html>
  );
}
